services:
  payload:
    image: node:20-alpine
    ports:
      - '3000:3000'
    volumes:
      - ..:/workspace
      - node_modules:/workspace/dev/node_modules
    working_dir: /workspace/dev
    command: sh -c "npm install --no-package-lock && npm run dev"
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
